### ISSUE TITLE
Error downloading http://download3.dfrobot.com.cn/FireBeetle/osx-xtensa-lx106-elf-gb404fb9-2.tar.gz

### ISSUE THREAD

**Issue by lpotter** [DFRobot/FireBeetle-ESP8266#3]
Trying to download board support package, but fails.
Error downloading http://download3.dfrobot.com.cn/FireBeetle/osx-xtensa-lx106-elf-gb404fb9-2.tar.gz

**Comment by qsjhyy** [comment]
This can also be a problem with network fluctuations, so try multiple downloads. Or you can clone the library, manually add it to the appropriate Arduino IDE directory, download it again and install it directly.

**Comment by qsjhyy** [comment]
Due to a lack of further communication for an extended period, this issue has been closed. If there is a need in the future, it can be reopened at any time.
