### ISSUE TITLE
not compatible with blinker IoT Platform 与点灯科技不兼容

### ISSUE THREAD

**Issue by kamabokowen** [DFRobot/FireBeetle-ESP8266#4]
can not successfully verified 没办法正常编译
Blinker 版本是 0.3.7

**Comment by kamabokowen** [comment]
Blinker要求 ESP8266库文件版本是2.7.4以上，请问我可以直接使用Arduino官方的ESP8266库文件吗
我是在用Wifi bee模块

**Comment by qsjhyy** [comment]
I apologize for not paying attention to this repository earlier, which resulted in me not receiving an email notification for new issues. The current situation is that the JSON link has been deprecated. Please use http://download.dfrobot.top/FireBeetle/package_DFRobot_index.json or https://download.dfrobot.top/boards/package_DFRobot_index.json instead.

**Comment by qsjhyy** [comment]
使用新的链接也许可以解决你之前的问题。

**Comment by qsjhyy** [comment]
Due to a lack of further communication for an extended period, this issue has been closed. If there is a need in the future, it can be reopened at any time.
