### ISSUE TITLE
Failed to install platform Firebeetle ESP8266

### ISSUE THREAD

**Issue by Francois06100** [DFRobot/FireBeetle-ESP8266#5]
The installation of the board FireBeetle-ESP8266 on the boards manager of Arduino IDE using these links doesn't work :

http://download.dfrobot.top/FireBeetle/package_firebeetle8266_index.json
or
https://raw.githubusercontent.com/DFRobot/FireBeetle-ESP8266/master/package_firebeetle8266_index.json

It failed with the following error :

Failed to install platform: firebeetle8266:firebeetle8266.
Error: 9 FAILED_PRECONDITION: Platform 'firebeetle8266:firebeetle8266@2.3.3' not found: getting tool dependencies for platform firebeetle8266:firebeetle8266@2.3.3: tool mkspiffs not found

The bug is well explained at post #6 by ptillisch on this thread : 
https://forum.arduino.cc/t/failed-to-install-platform-firebeetle-esp8266/986142/6

**Comment by kamabokowen** [comment]
They are currently spending the Labor Day holiday and I am expecting that they will fix the problem soon.
I have encountered that the library version they provide is too low to work with other library files, will your development board work properly with the official Arduino library files "Generic ESP8266 Module"?

**Comment by Francois06100** [comment]
Thanks for the answer. That's what I'm gonna do in the meantime : try the Generic ESP8266 Module instead.

**Comment by Andrea1971-Sketch** [comment]
When do they intend to fix this persisting issue?
Is quite disappointing to wait for months for a fix.

**Comment by kamabokowen** [comment]
> 

They seem to have given up on the project. 
I later used a generic ESP8266 module by flying the wire. 
You just need to connect the corresponding pin definitions one to one and it should work.
Hope this can help you.

**Comment by Andrea1971-Sketch** [comment]
Thank you for your reply and welcomed help. Since I am new with these matters, I do not understand the jargon at full. So I need to ask basic questions:

What do you mean with “Module”?
You refer to the Json-Reference or another micro- controller.

With Pin Definitions you intend the corresponding micro-controller pins, or else?

Using Arduino IDE and programming is not an issue, I just do not find a solution to configure the FireBeetle ESP8266 as any other one (..)

Thank you for helping out, much appreciated.

**Comment by kamabokowen** [comment]
> 

I am not a native English speaker, so please understand if some of my wording is inaccurate.
This project applies to two kinds of ESP8266 products they developed, one is FireBeetle Board-ESP8266, which is an ESP8266 development board. [Official Website for FireBeetle Board-ESP8266](https://wiki.dfrobot.com.cn/_SKU_DFR0489_FireBeetle_Board_ESP8266%E4%B8%BB%E6%9D%BF%E6%8E%A7%E5%88%B6%E5%99%A8V2_0)
The other one is WiFi Bee-ESP8266 wireless module [Official Website for WiFi Bee-ESP8266](https://wiki.dfrobot.com.cn/_SKU_TEL0092_WiFi_Bee-ESP8266_%E6%97%A0%E7%BA%BF%E6%A8%A1%E5%9D%97)

The URL mentioned above is their Chinese product database. The server is in China, you may encounter connection problems if you access it from non-mainland China. The project I was using this product for was to use it as an upper. So then I simply used the generic ESP8266 development board instead. For now I don't know the actual purpose for using this development board. If possible, please try to switch your project to a generic ESP8266 development board. By the way, the main developers of this project are actually still active on github, but maybe they have basically given up on the project now. 
Anyway, good luck to you!

**Comment by qsjhyy** [comment]
I apologize for not paying attention to this repository earlier, which resulted in me not receiving an email notification for new issues. The current situation is that the JSON link has been deprecated. Please use http://download.dfrobot.top/FireBeetle/package_DFRobot_index.json or https://download.dfrobot.top/boards/package_DFRobot_index.json instead.

**Comment by qsjhyy** [comment]
Due to a lack of further communication for an extended period, this issue has been closed. If there is a need in the future, it can be reopened at any time.
